language: node_js
node_js:
  - '6'
cache:
  directories:
    - node_modules

after_success:
  - pwd
  - ls -al
  - mkdir codedeploy_artifact
  - cp ./infrastructure/aws/codedeploy/*.sh .
  - cp ./infrastructure/aws/codedeploy/*.yml .
  - zip -r csye6225-web-app-$TRAVIS_JOB_NUMBER.zip ./webapp/  *.sh *.yml
  - mv csye6225-web-app-$TRAVIS_JOB_NUMBER.zip codedeploy_artifact/
  - ls -al
  - pwd
  - cd codedeploy_artifact
  - ls -al
  - pwd
  - cd ..
  - pwd
  - ls -al

deploy:
  - provider: s3
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    local_dir: codedeploy_artifact
    skip_cleanup: true
    on: 
      branch: master
    bucket: $s3_bucket
    region: us-east-1

  - provider: codedeploy
    access_key_id: $access_key_id
    bucket: $s3_bucket
    key: csye6225-web-app-$TRAVIS_JOB_NUMBER.zip
    bundle_type: zip
    application: $application
    deployment_group: $deployment_group
    region: us-east-1
    secret_access_key: $secret_access_key
    wait-until-deployed: true
    on:
      branch: master

script:
  - pwd
  - ls -al
  
